### ISSUE TITLE
Deployment exception

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-opentracing#24]
When deploying an application using Thorntail 2.2.0.Final that has the `microprofile` fraction present, it fails to deploy through the RHOAR Launcher with the following error:

```
2018-09-11 19:57:35,958 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 5) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: RESTEASY003325: Failed to construct public io.smallrye.opentracing.SmallRyeTracingDynamicFeature()
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
  at org.jboss.threads.JBossThread.run(JBossThread.java:320)
 Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public io.smallrye.opentracing.SmallRyeTracingDynamicFeature()
  at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.injectedInstance(ResteasyProviderFactory.java:2324)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1754)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1396)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1317)
  at org.jboss.resteasy.spi.ResteasyDeployment.registerProvider(ResteasyDeployment.java:607)
  at org.jboss.resteasy.spi.ResteasyDeployment.registration(ResteasyDeployment.java:391)
  at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:258)
  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
  at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
  at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
  at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
  at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
  at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
  at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
  at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
  at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
  at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
  at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
  ... 6 more
 Caused by: java.lang.IllegalStateException: Singleton not set for STATIC_INSTANCE => []
  at org.jboss.weld.bootstrap.api.helpers.RegistrySingletonProvider$RegistrySingleton.get(RegistrySingletonProvider.java:28)
  at org.jboss.weld.Container.instance(Container.java:53)
  at org.jboss.as.weld.WeldProvider.getCDI(WeldProvider.java:61)
  at javax.enterprise.inject.spi.CDI.current(CDI.java:60)
  at io.smallrye.opentracing.SmallRyeTracingDynamicFeature.<init>(SmallRyeTracingDynamicFeature.java:23)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
  ... 31 more
```

**Comment by kenfinnigan** [comment]
@pavolloffay FYI

**Comment by pavolloffay** [comment]
There is missing beans.xml. The same was fixed here https://github.com/thorntail/thorntail-examples/pull/187.

**Comment by pavolloffay** [comment]
We could catch the exception and log the state. However as these specs depends on CDI isn't it expected that boosters/generators provide `beans.xml` in the archive?

**Comment by kenfinnigan** [comment]
I'm such an idiot, thanks @pavolloffay. Completely forgot that beans.xml is needed!
