### ISSUE TITLE
Flaky tck

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentracing#54]
Sometimes I get the following failure when running TCK:
```
[ERROR] Tests run: 63, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 58.098 s <<< FAILURE! - in TestSuite
[ERROR] testClientNotTraced(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testNotTraced(OpenTracingMpRestClientTests.java:120)
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testClientNotTraced(OpenTracingMpRestClientTests.java:110)

[ERROR] testMethodNotTraced(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testNotTraced(OpenTracingMpRestClientTests.java:120)
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testMethodNotTraced(OpenTracingMpRestClientTests.java:116)

[ERROR] testMultithreadedNestedSpans(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.018 s  <<< FAILURE!
java.util.concurrent.ExecutionException: java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testMultithreadedNestedSpans(OpenTracingMpRestClientTests.java:86)
Caused by: java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.executeNested(OpenTracingMpRestClientTests.java:183)

[ERROR] testMultithreadedNestedSpansAsync(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.02 s  <<< FAILURE!
java.util.concurrent.ExecutionException: java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testMultithreadedNestedSpansAsync(OpenTracingMpRestClientTests.java:104)
Caused by: java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.executeNested(OpenTracingMpRestClientTests.java:183)

[ERROR] testNestedSpans(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 0.027 s  <<< FAILURE!
java.lang.AssertionError: Expected HTTP response code 200 but received 500; Response: 
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.executeNested(OpenTracingMpRestClientTests.java:183)
	at org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests.testNestedSpans(OpenTracingMpRestClientTests.java:65)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testClientNotTraced:110->testNotTraced:120->OpenTracingBaseTests.executeRemoteWebServiceRaw:147->OpenTracingBaseTests.executeRemoteWebServiceRaw:169 Expected HTTP response code 200 but received 500; Response: 
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testMethodNotTraced:116->testNotTraced:120->OpenTracingBaseTests.executeRemoteWebServiceRaw:147->OpenTracingBaseTests.executeRemoteWebServiceRaw:169 Expected HTTP response code 200 but received 500; Response: 
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testMultithreadedNestedSpans:86->OpenTracingBaseTests.testMultithreadedNestedSpans:417 » Execution
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testMultithreadedNestedSpansAsync:104->OpenTracingBaseTests.testMultithreadedNestedSpans:417 » Execution
[ERROR]   OpenTracingMpRestClientTests>Arquillian.run:138->testNestedSpans:65->OpenTracingBaseTests.testNestedSpans:380->executeNested:183->OpenTracingBaseTests.executeRemoteWebServiceRaw:169 Expected HTTP response code 200 but received 500; Response: 
[INFO] 
[ERROR] Tests run: 63, Failures: 5, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] smallrye-opentracing-parent ........................ SUCCESS [  0.166 s]
[INFO] smallrye-opentracing ............................... SUCCESS [  1.251 s]
[INFO] smallrye-opentracing-tck ........................... FAILURE [01:01 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

**Comment by pavolloffay** [comment]
Here is full server log https://pastebin.com/LCdB62ju.

Here is the last part of the log:
```
2019-02-21 14:52:50,712 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 27) WFLYUT0021: Registered web context: '/opentracing' for server 'default-server'
2019-02-21 14:52:50,736 INFO  [org.jboss.as.server] (management-handler-thread - 2) WFLYSRV0010: Deployed "opentracing.war" (runtime-name : "opentracing.war")
2019-02-21 14:52:51,025 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 27) WFLYUT0022: Unregistered web context: '/opentracing' from server 'default-server'
2019-02-21 14:52:51,037 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /opentracing/rest/mpRestClient/nestedMpRestClient: javax.servlet.ServletException: UT010051: Deployment opentracing.war has stopped
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:56)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
```

The `RestClientServices` rest resource if deployed fine but than the deployment stops. 

@kenfinnigan do you know why it could happen?
